import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillTwitterCircle , AiFillLinkedin, AiFillYouTube, AiFillGithub} from 'react-icons/ai'
import Image from 'next/image'
import { useState } from "react";
import deved from "../public/aryanpfp1.png";
import projectss1 from "../public/ytcone.png"
import projectss2 from "../public/text-utils.png"

import Buttons from '../components/buttons';
import Card from '../components/cards';


export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Aryan Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-navy-blue'>
        <section className='lg:min-h-screen md:min-h-screen'>
          
        <nav className="bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-navy-blue">
          <div className="container flex flex-wrap items-center justify-between mx-auto">
          <h1 className='text-xl font-burtons dark:text-emerald-400  '><a href="/">Aryan</a></h1>
            
            <div className=" w-full md:block md:w-auto" id="navbar-default">
              <ul className="flex flex-col p-4 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-navy-blue md:dark:bg-navy-blue dark:border-navy-blue">
                <li onClick={()=> setDarkMode(!darkMode)} className="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"><BsFillMoonStarsFill 
                      
                      className='cursor-pointer text-2xl bg-b dark:text-gray-300'/></li>
                <li>
                  <a href="#About" className="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">About</a>
                </li>
                <li>
                  <a href="#Projects" className="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Project</a>
                </li>
                <li>
                  <a href="#Contact" className="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Contact</a>
                </li>
                <li>
                  <a href="https://drive.google.com/file/d/1FrJvldgV05p_9dT6USiEs1Po1kIVlOkA/view?usp=share_link" className="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Resume</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
          <div className='text-center p-10 mt-10 pt-0'>
          <h4 className=' text-sm dark:text-gray-300'>Hi, my name is </h4>
            <h1 className='text-5xl py-3 text-teal-600 font-medium md:text-6  xl dark:text-teal-400 '>Aryan Bhokare</h1>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Web Developer and C++ Programmer</h3>
            
            <p className='text-md py-2 leading-8 text-gray-800 max-w-xl mx-auto dark:text-custom-slate'> I’m a software developer specializing in building (and occasionally designing). Currently, I’m focused on learning Backend technologies and Machine Learning  </p>
          </div>
          <div className='flex justify-center
           space-x-2 text-4xl py-3 gap-10 dark:text-gray-200'>
            <a href="https://github.com/aryan-bhokare"><AiFillGithub/></a>
            <a href="https://www.linkedin.com/in/aryan-b-3803751a7/"><AiFillLinkedin /></a>
            <a href="https://twitter.com/aryan_okidoki"><AiFillTwitterCircle/></a>
            
          </div>
          <div className='relative bg-gradient-to-b from-teal-500 rounded-full my-6 w-80 h-80 mx-auto overflow-hidden'>
            <Image fill style={{objectFit:"cover"}} src={deved} />
          </div>
        </section>



        <section id="About" >
          <div className='pt-20'>
            <h3 className="text-3xl py-1 mt-3 font-bold dark:text-white text-center ">About me</h3>
            <p className="text-lg py-2 pl-2 leading-8 text-gray-800 dark:text-gray-200">
            Here you will find more information about me, what I do, and my current skills mostly in terms of programming and technology
            </p>
            <div className='grid grid-cols-1 md:grid-cols-2 p-2 py-3 gap-8'>
              <div>
                <h1 className=' text-lg font-bold dark:text-white'>Get to know me!</h1>
                <h2 className=' dark:text-white'>I'm a Frontend Web Developer building the Front-end of Websites and Web Applications that leads to the success of the overall product. Check out some of my work in the Projects section.

                I also like sharing content related to the stuff that I have learned over the years in Web Development so it can help other people of the Dev Community. Feel free to Connect or Follow me on my Linkedin where I post useful content related to Web Development and Programming

                I'm open to Job opportunities where I can contribute, learn and grow. If you have a good opportunity that matches my skills and experience then don't hesitate to contact me.</h2>
              </div>
              <div className='text-lg dark:text-white'>
                <h1 className='font-bold dark:text-white'>My Skills</h1>
                <div className='flex flex-wrap p-2'>
                <Buttons name="React js"/>
                <Buttons name="Tailwind Css"/>
                <Buttons name="JavaScript Advance"/>
                <Buttons name="Node js Intermediate"/>
                <Buttons name="Express js"/>
                <Buttons name="Python"/>
                <Buttons name="NumPy"/>
                <Buttons name="Pandas"/>
                <Buttons name="Git and Github"/>
                <Buttons name="MongoDB"/>
                <Buttons name="Rest APIs"/>
                
                </div>
              </div>
            </div>
          </div> 
        </section>
        <section id="Projects" className="py-10">
         <h1 className="text-3xl py-2 mb-10 mt-3 font-bold dark:text-white ">Projects</h1>
          <div  className='grid md:grid-cols-3'>
            <Card
            projectname="YoutubeClone"
            source={projectss1}
            projectinfo="
            YouTube (Video streaming) Clone web app made with the help of YouTube API from Rapid API. 
            Used React Hooks and React Router to make the site responsive.
            Interactive and responsive design.
            Tech stack used HTML,Tailwind CSS,Material UI, JavaScript, ReactJs, Rapid API.
            "
            githublink="https://github.com/aryan-bhokare/Youtube-Clone"
            />
            <Card
            projectname="Text-Utils"
            source={projectss2}
            projectinfo="
            Text-utils is a text utility platform where you can make changes to the text like making it bold, lowercase and uppercase very conviniently. It supports the Dark mode feature made with the help of React hooks.
            Tech stack used HTML,Tailwind CSS, JavaScript, React."
            githublink="https://github.com/aryan-bhokare/textutils"
            />
            {/* <Card
            projectname="Expense Tracker"
            source={}
            projectinfo="
            YouTube (Video streaming) Clone web app made with the help of YouTube API from Rapid API. 
            Tech stack used HTML,Tailwind CSS, JavaScript, ReactJs, Rapid API.
            Interactive and responsive design."
            githublink="https://github.com/aryan-bhokare/Youtube-Clone"
            /> */}
          </div>
        </section>  
        <section id='Contact'>
       
            <h1 className="text-3xl py-2 mb-10 mt-3 font-bold dark:text-white text-center">Get In Touch</h1>
            <p className="text-lg py-2 pl-2 leading-8 text-gray-800 dark:text-gray-200">
            Feel free to Contact me by submitting the form below and I will get back to you as soon as possible.
            Also if you want to share any opportunities
            </p>
            <div className='text-center'>
            <button className='relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-green-400 to-blue-600 group-hover:from-green-400 group-hover:to-blue-600 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-green-200 dark:focus:ring-green-800'>
                <a className= 'relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0' href="mailto:aryan1bhokare@gmail.com">Email me</a>
              </button>            
              </div>  
             </section>
        
      </main>
    </div>
  )
}
